import type { TCard } from '@battleground/validators';

export const CARD_BG_IMAGE_MAP: Record<TCard | 'redacted', string> = {
  A2: '/cards/A2.png',
  A3: '/cards/A3.png',
  A4: '/cards/A4.png',
  A5: '/cards/A5.png',
  A6: '/cards/A6.png',
  A7: '/cards/A7.png',
  A8: '/cards/A8.png',
  S2: '/cards/S2.png',
  S3: '/cards/S3.png',
  S4: '/cards/S4.png',
  S5: '/cards/S5.png',
  S6: '/cards/S6.png',
  S7: '/cards/S7.png',
  S8: '/cards/S8.png',
  H2: '/cards/H2.png',
  H3: '/cards/H3.png',
  H4: '/cards/H4.png',
  H5: '/cards/H5.png',
  H6: '/cards/H6.png',
  H7: '/cards/H7.png',
  H8: '/cards/H8.png',
  redacted: '/cards/redacted.png',
};
