import type { TCard } from '@battleground/validators';

export const CARD_COLOR_MAP: Record<TCard | 'redacted', string> = {
  A2: 'bg-red-200',
  A3: 'bg-orange-200',
  A4: 'bg-amber-200',
  A5: 'bg-yellow-200',
  A6: 'bg-lime-200',
  A7: 'bg-green-200',
  A8: 'bg-emerald-200',
  S2: 'bg-teal-200',
  S3: 'bg-cyan-200',
  S4: 'bg-sky-200',
  S5: 'bg-blue-200',
  S6: 'bg-indigo-200',
  S7: 'bg-violet-200',
  S8: 'bg-purple-200',
  H2: 'bg-fuchsia-200',
  H3: 'bg-pink-200',
  H4: 'bg-rose-200',
  H5: 'bg-slate-200',
  H6: 'bg-gray-200',
  H7: 'bg-zinc-200',
  H8: 'bg-stone-200',
  redacted: 'bg-gray-500',
};

export const CARD_BG_IMAGE_MAP: Record<TCard | 'redacted', string> = {
  A2: '/cards/archer.png',
  A3: '/cards/archer.png',
  A4: '/cards/archer.png',
  A5: '/cards/archer.png',
  A6: '/cards/archer.png',
  A7: '/cards/archer.png',
  A8: '/cards/archer.png',
  S2: '/cards/swordsman.png',
  S3: '/cards/swordsman.png',
  S4: '/cards/swordsman.png',
  S5: '/cards/swordsman.png',
  S6: '/cards/swordsman.png',
  S7: '/cards/swordsman.png',
  S8: '/cards/swordsman.png',
  H2: '/cards/horseman.png',
  H3: '/cards/horseman.png',
  H4: '/cards/horseman.png',
  H5: '/cards/horseman.png',
  H6: '/cards/horseman.png',
  H7: '/cards/horseman.png',
  H8: '/cards/horseman.png',
  redacted: '/cards/redacted.png',
};
